from __future__ import annotations

from typing import Any, Dict

SEARCH_DATA_SOURCES: Dict[str, Dict[str, Any]] = {
    "open_web": {
        "name_zh": "公开网页 / 搜索引擎",
        "source_names": ["Google", "Bing", "百度", "公开博客", "技术文档"],
        "purpose": "公开网页、产品资料、技术博客和公司公开信息",
        "talent_signals": ["公开作品", "技术观点", "产品资料", "团队动态", "引用来源"],
        "suggested_queries": [
            "家庭机器人 VLA 技术博客",
            "embodied AI robot demo engineer",
            "机器人 公司 产品 技术路线",
        ],
        "access_pattern": "优先使用官方搜索 API、站内搜索、RSS 或公开网页；遵守 robots.txt 和平台条款。",
        "risk_level": "medium",
        "freshness": "daily",
    },
    "recruitment_boards_cn": {
        "name_zh": "Boss / 猎聘 / 拉勾 / 智联",
        "source_names": ["Boss直聘", "猎聘", "拉勾", "智联招聘"],
        "purpose": "招聘岗位、薪酬、技能要求",
        "talent_signals": ["岗位需求", "薪酬区间", "技能关键词", "职级", "招聘热度"],
        "suggested_queries": [
            "具身智能 机器人 控制 薪酬",
            "VLA 世界模型 机器人 招聘",
            "机器人 数据采集 遥操作 岗位",
        ],
        "access_pattern": "优先使用授权账号、官方商业接口、人工导出或合规第三方数据服务；不在系统内做绕过登录或反爬采集。",
        "risk_level": "high",
        "freshness": "daily",
    },
    "linkedin": {
        "name_zh": "LinkedIn",
        "source_names": ["LinkedIn"],
        "purpose": "候选人履历、人才流动",
        "talent_signals": ["候选人履历", "公司流动", "团队规模", "海外人才线索", "职位变更"],
        "suggested_queries": [
            "embodied AI robotics world model engineer",
            "robotics control scientist MPC WBC",
            "VLA robotics research engineer",
        ],
        "access_pattern": "优先使用 LinkedIn 官方/授权产品、人工检索或候选人主动提供资料；注意个人数据合规和平台条款。",
        "risk_level": "high",
        "freshness": "weekly",
    },
    "company_websites": {
        "name_zh": "公司官网",
        "source_names": ["公司官网", "招聘页", "团队页", "博客", "技术白皮书"],
        "purpose": "产品、团队、技术方向",
        "talent_signals": ["产品路线", "技术栈", "团队负责人", "招聘方向", "客户案例"],
        "suggested_queries": [
            "site:company.com robotics embodied AI",
            "site:company.com careers robot learning",
            "site:company.com world model robotics",
        ],
        "access_pattern": "公开网页抓取前遵守 robots.txt；优先 RSS、站内搜索、公开新闻稿和招聘页。",
        "risk_level": "medium",
        "freshness": "weekly",
    },
    "github": {
        "name_zh": "GitHub",
        "source_names": ["GitHub"],
        "purpose": "工程能力、开源贡献",
        "talent_signals": ["代码质量", "开源贡献", "提交活跃度", "项目影响力", "机器人相关仓库"],
        "suggested_queries": [
            "diffusion policy robotics language:Python",
            "VLA robot policy",
            "MPC WBC locomotion",
        ],
        "access_pattern": "使用 GitHub API 或公开搜索；需要 token 时使用环境变量，不硬编码密钥。",
        "risk_level": "low",
        "freshness": "daily",
    },
    "model_hubs": {
        "name_zh": "Hugging Face / ModelScope",
        "source_names": ["Hugging Face", "ModelScope"],
        "purpose": "模型、数据集、Demo、Space 和开源影响力",
        "talent_signals": ["模型发布", "数据集贡献", "Space Demo", "下载量", "社区讨论"],
        "suggested_queries": [
            "robotics VLA dataset Hugging Face",
            "embodied AI policy ModelScope",
            "robot manipulation demo space",
        ],
        "access_pattern": "使用官方 API、公开项目页或人工整理；记录模型/数据集 license 和发布日期。",
        "risk_level": "low",
        "freshness": "daily",
    },
    "scholar_arxiv": {
        "name_zh": "Google Scholar / arXiv",
        "source_names": ["Google Scholar", "arXiv"],
        "purpose": "学术能力、论文方向",
        "talent_signals": ["论文主题", "作者", "引用", "机构", "研究方向演进"],
        "suggested_queries": [
            "embodied AI world model robotics",
            "vision language action robot manipulation",
            "model predictive control humanoid robot",
        ],
        "access_pattern": "arXiv 使用公开 API；Google Scholar 优先人工检索或合规第三方服务，不做高频抓取。",
        "risk_level": "medium",
        "freshness": "weekly",
    },
    "openalex_author_institution_search": {
        "name_zh": "OpenAlex 作者 / 机构",
        "source_names": ["OpenAlex Authors", "OpenAlex Institutions", "OpenAlex Works"],
        "source_type": "academic_author_institution",
        "purpose": "检索论文作者、机构、学校、实验室方向、引用和研究主题，用于学术人才来源和团队方向判断",
        "talent_signals": ["作者", "机构", "学校", "实验室方向", "引用", "论文数量", "主题"],
        "suggested_queries": [
            "robot learning Zhejiang University OpenAlex author",
            "Shanghai Jiao Tong robotics institution OpenAlex",
            "embodied AI lab OpenAlex authors institutions",
        ],
        "access_pattern": "使用 OpenAlex 官方 API；保留作者/机构 ID、homepage、works_count、cited_by_count 和检索时间。",
        "risk_level": "low",
        "freshness": "weekly",
    },
    "semantic_scholar_research": {
        "name_zh": "Semantic Scholar 论文 / 作者",
        "source_names": ["Semantic Scholar Graph API", "Semantic Scholar Papers", "Semantic Scholar Authors"],
        "source_type": "academic",
        "purpose": "检索论文、作者、摘要、引用、venue、h-index 和开放访问链接，补 OpenAlex 的论文/作者证据",
        "talent_signals": ["论文", "作者", "引用", "venue", "h-index", "open access", "研究方向"],
        "suggested_queries": [
            "Vision Language Action Robotics Semantic Scholar",
            "robot foundation model author h-index",
            "robot manipulation CoRL Semantic Scholar",
        ],
        "access_pattern": "使用 Semantic Scholar Graph API；遵守接口限额，保留 paperId/authorId、URL 和字段来源。",
        "risk_level": "low",
        "freshness": "weekly",
    },
    "patent_databases": {
        "name_zh": "专利数据库",
        "source_names": ["Google Patents", "国家知识产权局", "Lens", "智慧芽"],
        "purpose": "技术发明人和公司技术布局",
        "talent_signals": ["发明人", "申请人", "技术方向", "专利族", "公司布局"],
        "suggested_queries": [
            "humanoid robot dexterous hand actuator",
            "robot world model motion planning",
            "机器人 灵巧手 触觉 发明人",
        ],
        "access_pattern": "优先公开检索、授权数据库 API 或人工导出；保留来源和公开状态。",
        "risk_level": "medium",
        "freshness": "monthly",
    },
    "business_databases_cn": {
        "name_zh": "企查查 / 天眼查",
        "source_names": ["企查查", "天眼查"],
        "purpose": "公司工商、融资、股权",
        "talent_signals": ["工商主体", "融资轮次", "股东", "高管", "关联公司"],
        "suggested_queries": [
            "具身智能 机器人 融资",
            "人形机器人 公司 股权",
            "机器人 创业公司 工商",
        ],
        "access_pattern": "使用官方商业接口或人工授权导出；不绕过付费墙或访问控制。",
        "risk_level": "high",
        "freshness": "weekly",
    },
    "news_media": {
        "name_zh": "新闻媒体",
        "source_names": ["36氪", "晚点", "机器之心", "量子位", "TechCrunch", "The Robot Report"],
        "purpose": "融资、产品发布、团队动态",
        "talent_signals": ["融资新闻", "产品发布", "核心成员", "客户合作", "战略变化"],
        "suggested_queries": [
            "具身智能 融资 团队",
            "humanoid robot funding team",
            "world model robotics product launch",
        ],
        "access_pattern": "使用公开 RSS、新闻搜索 API、站内搜索或授权媒体数据库；记录发布时间。",
        "risk_level": "low",
        "freshness": "daily",
    },
    "ai_communities": {
        "name_zh": "AI 社区 / 论坛",
        "source_names": ["AI 论坛", "Discord", "微信群", "知乎", "即刻", "Reddit"],
        "purpose": "年轻高潜人才、技术讨论、项目传播和社区影响力",
        "talent_signals": ["技术讨论", "项目分享", "社区声量", "同行推荐", "问题解法"],
        "suggested_queries": [
            "Reddit embodied AI robot learning",
            "知乎 具身智能 VLA 项目",
            "Discord robotics diffusion policy",
        ],
        "access_pattern": "优先使用公开页面、官方 API、授权社群整理或人工记录；不采集私域敏感信息。",
        "risk_level": "high",
        "freshness": "daily",
    },
    "agent_reach_social_search": {
        "name_zh": "Agent-Reach 社媒搜索",
        "source_names": ["Agent-Reach", "OpenCLI", "微博", "B站", "V2EX", "知乎", "掘金", "CSDN", "SegmentFault", "X/Twitter", "Reddit", "YouTube", "小红书", "抖音", "公众号"],
        "source_type": "social_platform_search",
        "purpose": "跨社媒、论坛和垂直平台搜索/读取公开讨论、视频字幕、评论和账号公开职业线索",
        "talent_signals": ["社媒讨论", "论坛帖子", "公开视频", "公开评论", "项目传播", "社区影响力", "公开职业线索"],
        "suggested_queries": [
            "Agent-Reach OpenCLI 微博 B站 V2EX 具身智能",
            "小红书 具身智能 机器人 Demo",
            "知乎 掘金 CSDN SegmentFault 机器人 VLA 项目",
        ],
        "access_pattern": "安装 Agent-Reach 后仅使用公开页面、官方 API、用户授权登录态或人工导出；不绕过平台访问控制。",
        "risk_level": "high",
        "freshness": "daily",
    },
    "opencli_crawl_scrape": {
        "name_zh": "OpenCLI 本地网页抓取",
        "source_names": ["OpenCLI", "公开网页", "授权网页", "本地 CLI 抓取"],
        "source_type": "adaptive_web_scraping",
        "purpose": "通过本地 opencli 命令抓取公开或已授权页面，补学校官网、论坛帖子、候选人主页和竞赛页面正文。",
        "talent_signals": ["网页正文", "页面标题", "公开主页", "竞赛页面", "学校/实验室成员页", "论坛帖子"],
        "suggested_queries": [
            "opencli web read university robotics lab team",
            "opencli web read 机器人 实验室 成员",
            "opencli web read 竞赛 获奖名单 AI 机器人",
        ],
        "access_pattern": "只针对公开或明确授权 URL；命令本地执行，不走 shell；必须遵守 robots、平台条款、速率限制、域名边界和数据最小化。",
        "risk_level": "high",
        "freshness": "on_demand",
    },
    "opencli_platform_search": {
        "name_zh": "OpenCLI 平台搜索",
        "source_names": ["OpenCLI", "B站", "知乎", "小红书", "LinkedIn", "YouTube", "X/Twitter", "Reddit", "微信公众号"],
        "source_type": "browser_platform_search",
        "purpose": "通过 OpenCLI 内置平台命令读取授权浏览器中的社媒、论坛、公众号文章、视频和职业主页线索。",
        "talent_signals": ["公开视频", "技术问答", "公开主页", "职业履历", "推文", "论坛帖子", "公众号文章", "项目传播", "社区影响力"],
        "suggested_queries": [
            "opencli bilibili search 具身智能 VLA Demo",
            "opencli zhihu search 机器人 Diffusion Policy",
            "opencli twitter search robotics diffusion policy",
            "opencli reddit search embodied AI robotics",
            "opencli weixin search 具身智能 机器人 招聘",
            "opencli linkedin people-search robotics foundation model",
        ],
        "access_pattern": "需要本地 opencli 和 Browser Bridge；仅使用公开页面、官方站点行为或用户授权登录态，不绕过访问控制。",
        "risk_level": "high",
        "freshness": "daily",
    },
    "opencli_web_read_search": {
        "name_zh": "OpenCLI 网页正文读取",
        "source_names": ["OpenCLI", "公开网页", "授权网页", "网页正文", "Browser Bridge"],
        "source_type": "adaptive_web_scraping",
        "purpose": "将已发现的公开或明确授权 URL 转为正文证据，服务 crawler snapshot 和证据链补全。",
        "talent_signals": ["网页正文", "页面标题", "公开主页", "实验室成员页", "竞赛页面", "候选人博客"],
        "suggested_queries": [
            "opencli web read https://example.edu/robotics/team",
            "opencli web read https://example.com/careers/robotics",
            "opencli web read https://example.org/competition/winners",
        ],
        "access_pattern": "只读取绝对 http(s) URL；需要 Browser Bridge；遵守 robots、平台条款、速率限制、域名边界和数据最小化。",
        "risk_level": "high",
        "freshness": "on_demand",
    },
    "ai_events": {
        "name_zh": "AI 活动 / 会议",
        "source_names": ["Hackathon", "Meetup", "会议", "直播", "Workshop"],
        "purpose": "活动参与者、演讲嘉宾、获奖项目和新兴团队线索",
        "talent_signals": ["参赛项目", "获奖名单", "演讲主题", "组织者", "Demo 展示"],
        "suggested_queries": [
            "robotics hackathon embodied AI winner",
            "具身智能 Meetup 机器人 Demo",
            "VLA Workshop speaker robotics",
        ],
        "access_pattern": "使用活动官网、公开议程、公开直播页或主办方授权名单；记录活动日期和来源。",
        "risk_level": "medium",
        "freshness": "per_event",
    },
    "video_platforms": {
        "name_zh": "视频平台 / 字幕",
        "source_names": ["B站", "YouTube", "技术演讲", "Demo 视频", "字幕"],
        "purpose": "Demo 真实性、技术讲解、公开演讲和项目影响力",
        "talent_signals": ["Demo 质量", "演讲内容", "字幕关键词", "项目作者", "互动反馈"],
        "suggested_queries": [
            "B站 具身智能 机器人 Demo",
            "YouTube robot manipulation VLA demo",
            "机器人 技术演讲 字幕 世界模型",
        ],
        "access_pattern": "优先使用官方 API、公开字幕、公开视频元数据或人工标注；保留 URL、发布时间和转写来源。",
        "risk_level": "medium",
        "freshness": "weekly",
    },
    "filings_annual_reports": {
        "name_zh": "招股书 / 年报",
        "source_names": ["招股书", "年报", "SEC", "港交所披露易", "巨潮资讯"],
        "purpose": "上市公司业务和人员情况",
        "talent_signals": ["业务收入", "研发投入", "员工结构", "核心技术", "风险因素"],
        "suggested_queries": [
            "机器人 年报 研发人员",
            "robotics annual report R&D headcount",
            "招股书 具身智能 机器人",
        ],
        "access_pattern": "使用交易所/监管机构公开披露文件，保留文件版本、日期和页码。",
        "risk_level": "low",
        "freshness": "quarterly",
    },
    "university_labs": {
        "name_zh": "学校实验室官网",
        "source_names": ["高校实验室官网", "导师主页", "课题组新闻"],
        "purpose": "高校人才来源",
        "talent_signals": ["学生去向", "研究项目", "导师方向", "论文与代码", "毕业生"],
        "suggested_queries": [
            "site:edu robotics manipulation lab students",
            "具身智能 实验室 学生 去向",
            "robot learning lab alumni",
        ],
        "access_pattern": "使用公开网页、RSS 或人工整理；尊重个人信息边界，只采集公开职业线索。",
        "risk_level": "medium",
        "freshness": "monthly",
    },
    "education_competition_monitor": {
        "name_zh": "学校 / 竞赛监控",
        "source_names": ["高校官网", "实验室成员页", "天池", "DataFountain", "CCF", "ICPC", "CCPC", "蓝桥杯", "Kaggle"],
        "source_type": "school_competition_monitor",
        "purpose": "维护高校、实验室和竞赛公开页面监控目标，用于发现学生、导师、获奖团队、项目和高潜算法人才",
        "talent_signals": ["实验室成员", "导师方向", "论文项目", "竞赛获奖", "排行榜", "参赛团队", "学生去向"],
        "suggested_queries": [
            "机器人 天池 高校 实验室",
            "CCF BDCI 机器人 获奖 团队",
            "Kaggle robotics leaderboard university",
        ],
        "access_pattern": "先返回公开目标页和监控建议，再由快照 provider 定期抓取；不采集非公开学生信息或绕过登录。",
        "risk_level": "medium",
        "freshness": "weekly",
    },
    "conference_paper_lists": {
        "name_zh": "会议论文名单",
        "source_names": ["ICRA", "IROS", "CoRL", "RSS", "CVPR", "NeurIPS"],
        "purpose": "ICRA、IROS、CoRL、RSS、CVPR、NeurIPS 等人才线索",
        "talent_signals": ["论文作者", "机构", "方向", "共同作者网络", "代码链接"],
        "suggested_queries": [
            "CoRL VLA robot manipulation authors",
            "RSS world model robot learning",
            "ICRA humanoid whole body control",
        ],
        "access_pattern": "使用会议开放论文列表、OpenReview、Semantic Scholar、DBLP 或官方 proceedings。",
        "risk_level": "low",
        "freshness": "per_conference",
    },
    "regulatory_filings_global": {
        "name_zh": "全球监管披露 / 交易所公告",
        "source_names": ["SEC EDGAR", "港交所披露易", "巨潮资讯", "上交所", "深交所", "北交所"],
        "purpose": "一级/二级市场尽调中的招股书、年报、季报、重大公告、风险因素和管理层讨论",
        "talent_signals": ["研发投入", "员工结构", "核心技术", "客户集中度", "关联交易", "风险因素"],
        "suggested_queries": [
            "site:sec.gov robotics 10-K R&D headcount",
            "site:hkexnews.hk 机器人 招股书 研发",
            "site:cninfo.com.cn 机器人 年报 研发人员",
        ],
        "access_pattern": "优先使用监管机构和交易所公开披露入口；保留公告编号、发布日期、文件版本和页码。",
        "risk_level": "low",
        "freshness": "daily",
    },
    "funding_private_market": {
        "name_zh": "一级市场融资 / 私募股权数据库",
        "source_names": ["Crunchbase", "PitchBook", "IT桔子", "企名片", "36氪创投", "清科"],
        "purpose": "融资轮次、投资方、估值线索、竞品格局和公司成长阶段",
        "talent_signals": ["融资轮次", "投资方", "估值区间", "核心团队", "业务扩张", "裁员或收缩信号"],
        "suggested_queries": [
            "embodied AI robotics funding Series A",
            "人形机器人 融资 投资方 估值",
            "具身智能 创业公司 融资 团队",
        ],
        "access_pattern": "使用授权数据库、官方 API、公开新闻稿或人工导出；付费库不得绕过授权。",
        "risk_level": "high",
        "freshness": "weekly",
    },
    "market_data_secondary": {
        "name_zh": "二级市场行情 / 研究数据",
        "source_names": ["Wind", "同花顺 iFinD", "东方财富", "Yahoo Finance", "TradingView", "公司公告"],
        "purpose": "上市公司股价、估值、板块热度、机构研报引用和事件驱动信号",
        "talent_signals": ["市值变化", "估值倍数", "机构覆盖", "业务分部", "事件冲击", "研发投入趋势"],
        "suggested_queries": [
            "机器人 板块 研发投入 市值",
            "humanoid robotics public company revenue segment",
            "robotics stock earnings call R&D",
        ],
        "access_pattern": "使用授权金融终端、公开行情 API、交易所公告和公司投资者关系材料。",
        "risk_level": "medium",
        "freshness": "daily",
    },
    "earnings_calls_transcripts": {
        "name_zh": "业绩会纪要 / 电话会转写",
        "source_names": ["Seeking Alpha", "公司 IR", "交易所路演", "券商纪要", "FactSet"],
        "purpose": "管理层口径、产品节奏、客户验证、资本开支和业务风险",
        "talent_signals": ["管理层表述", "产品里程碑", "客户合作", "产能规划", "研发方向"],
        "suggested_queries": [
            "robotics earnings call transcript R&D",
            "humanoid robot investor relations transcript",
            "机器人 业绩会 纪要 研发",
        ],
        "access_pattern": "优先公司 IR 公开材料和授权数据库；券商纪要需确认授权和可引用范围。",
        "risk_level": "medium",
        "freshness": "quarterly",
    },
    "procurement_tenders": {
        "name_zh": "招投标 / 政府采购",
        "source_names": ["中国政府采购网", "公共资源交易中心", "公开采购门户", "TED", "企业采购公告"],
        "purpose": "真实客户、采购预算、交付能力、产品落地和竞争对手中标记录",
        "talent_signals": ["中标公司", "采购金额", "交付周期", "技术指标", "客户行业"],
        "suggested_queries": [
            "机器人 中标 公告 技术参数",
            "robotics tender award autonomous robot",
            "具身智能 采购 招标 项目",
        ],
        "access_pattern": "使用公开招投标网站、授权数据服务或人工整理；记录公告编号和发布日期。",
        "risk_level": "low",
        "freshness": "daily",
    },
    "supply_chain_import_export": {
        "name_zh": "供应链 / 进出口 / 海关数据",
        "source_names": ["Panjiva", "ImportGenius", "海关统计", "供应商官网", "BOM 公开资料"],
        "purpose": "关键供应商、出货、零部件路线、产能和客户关系线索",
        "talent_signals": ["供应商", "客户", "出货频次", "核心部件", "产能变化"],
        "suggested_queries": [
            "humanoid robot actuator supplier shipment",
            "机器人 减速器 供应商 客户",
            "robotics import export supplier",
        ],
        "access_pattern": "使用授权贸易数据库、公开海关统计和公司披露；不使用泄露或非授权商业数据。",
        "risk_level": "high",
        "freshness": "monthly",
    },
    "regulatory_risk_litigation": {
        "name_zh": "监管处罚 / 诉讼 / 失信风险",
        "source_names": ["裁判文书", "执行信息公开网", "SEC Enforcement", "FDA/工信部公告", "信用中国"],
        "purpose": "公司合规、诉讼、处罚、知识产权纠纷和经营风险",
        "talent_signals": ["诉讼主体", "处罚记录", "知识产权纠纷", "产品合规", "经营异常"],
        "suggested_queries": [
            "机器人 公司 诉讼 专利 纠纷",
            "robotics company litigation patent dispute",
            "site:sec.gov enforcement robotics",
        ],
        "access_pattern": "使用官方公开数据库和授权法律数据库；保留案号、公告日期和法院/监管机构。",
        "risk_level": "medium",
        "freshness": "weekly",
    },
    "app_traffic_product_analytics": {
        "name_zh": "App / 网站流量 / 产品数据",
        "source_names": ["Similarweb", "Sensor Tower", "七麦数据", "Google Trends", "百度指数"],
        "purpose": "产品热度、用户增长、地域分布、渠道变化和品牌声量",
        "talent_signals": ["流量趋势", "下载量", "用户评价", "关键词热度", "渠道投放"],
        "suggested_queries": [
            "robotics app downloads Sensor Tower",
            "机器人 App 下载量 用户评价",
            "具身智能 百度指数 Google Trends",
        ],
        "access_pattern": "使用公开趋势工具、授权数据平台或人工导出；第三方估算需标记置信度。",
        "risk_level": "medium",
        "freshness": "weekly",
    },
    "job_salary_labor_market": {
        "name_zh": "岗位薪酬 / 劳动力市场数据",
        "source_names": ["Levels.fyi", "薪智", "看准", "Boss直聘", "LinkedIn Jobs", "Indeed"],
        "purpose": "薪酬区间、岗位热度、技能需求、地区分布和团队扩张/收缩",
        "talent_signals": ["薪酬", "职位数量", "技能关键词", "职级", "地区", "岗位发布时间"],
        "suggested_queries": [
            "VLA robotics engineer salary",
            "具身智能 算法工程师 薪酬",
            "robot learning engineer jobs compensation",
        ],
        "access_pattern": "使用官方/授权招聘数据、公开页面和人工样本；不批量抓取登录后个人数据。",
        "risk_level": "high",
        "freshness": "daily",
    },
    "expert_network_interviews": {
        "name_zh": "专家访谈 / 人工调研",
        "source_names": ["专家网络", "客户访谈", "供应商访谈", "候选人访谈", "行业顾问"],
        "purpose": "验证公开信息无法确认的客户、供应链、技术成熟度和团队能力",
        "talent_signals": ["专家观点", "客户反馈", "供应商验证", "团队口碑", "技术成熟度"],
        "suggested_queries": [
            "机器人 行业专家 访谈 供应链",
            "embodied AI expert interview commercialization",
            "humanoid robot customer validation expert call",
        ],
        "access_pattern": "使用合规专家网络或人工访谈；记录访谈授权、时间、角色背景和可引用范围。",
        "risk_level": "high",
        "freshness": "per_interview",
    },
    "standards_certifications": {
        "name_zh": "标准 / 认证 / 安规",
        "source_names": ["ISO", "IEC", "IEEE", "工信部", "NIST", "UL", "CE"],
        "purpose": "产品准入、安全认证、行业标准、测试规范和量产约束",
        "talent_signals": ["认证状态", "标准参与", "安全测试", "准入门槛", "量产能力"],
        "suggested_queries": [
            "humanoid robot safety standard certification",
            "机器人 安规 认证 ISO IEC",
            "robotics UL CE certification",
        ],
        "access_pattern": "使用标准组织、监管机构和认证机构公开信息；付费标准正文需遵守授权。",
        "risk_level": "medium",
        "freshness": "monthly",
    },
    "datasets_benchmarks": {
        "name_zh": "数据集 / Benchmark / Leaderboard",
        "source_names": ["Papers with Code", "Open X-Embodiment", "Hugging Face Datasets", "OpenReview", "EvalAI"],
        "purpose": "技术真实性、模型效果、数据规模、复现实验和团队工程深度",
        "talent_signals": ["榜单成绩", "数据集贡献", "复现代码", "评测指标", "模型卡"],
        "suggested_queries": [
            "VLA robotics benchmark leaderboard",
            "Open X-Embodiment dataset contributors",
            "robot manipulation benchmark Papers with Code",
        ],
        "access_pattern": "使用公开榜单、论文、模型卡和数据集 license；记录版本、指标定义和评测时间。",
        "risk_level": "low",
        "freshness": "weekly",
    },
}
