from __future__ import annotations

from typing import Any, Dict

SEARCH_DATA_SOURCES: Dict[str, Dict[str, Any]] = {
    "open_web": {
        "name_zh": "公开网页 / 搜索引擎",
        "source_names": ["Google", "Bing", "百度", "公开博客", "技术文档"],
        "purpose": "公开网页、产品资料、技术博客和公司公开信息",
        "talent_signals": ["公开作品", "技术观点", "产品资料", "团队动态", "引用来源"],
        "suggested_queries": [
            "家庭机器人 VLA 技术博客",
            "embodied AI robot demo engineer",
            "机器人 公司 产品 技术路线",
        ],
        "access_pattern": "优先使用官方搜索 API、站内搜索、RSS 或公开网页；遵守 robots.txt 和平台条款。",
        "risk_level": "medium",
        "freshness": "daily",
    },
    "recruitment_boards_cn": {
        "name_zh": "Boss / 猎聘 / 拉勾 / 智联",
        "source_names": ["Boss直聘", "猎聘", "拉勾", "智联招聘"],
        "purpose": "招聘岗位、薪酬、技能要求",
        "talent_signals": ["岗位需求", "薪酬区间", "技能关键词", "职级", "招聘热度"],
        "suggested_queries": [
            "具身智能 机器人 控制 薪酬",
            "VLA 世界模型 机器人 招聘",
            "机器人 数据采集 遥操作 岗位",
        ],
        "access_pattern": "优先使用授权账号、官方商业接口、人工导出或合规第三方数据服务；不在系统内做绕过登录或反爬采集。",
        "risk_level": "high",
        "freshness": "daily",
    },
    "linkedin": {
        "name_zh": "LinkedIn",
        "source_names": ["LinkedIn"],
        "purpose": "候选人履历、人才流动",
        "talent_signals": ["候选人履历", "公司流动", "团队规模", "海外人才线索", "职位变更"],
        "suggested_queries": [
            "embodied AI robotics world model engineer",
            "robotics control scientist MPC WBC",
            "VLA robotics research engineer",
        ],
        "access_pattern": "优先使用 LinkedIn 官方/授权产品、人工检索或候选人主动提供资料；注意个人数据合规和平台条款。",
        "risk_level": "high",
        "freshness": "weekly",
    },
    "company_websites": {
        "name_zh": "公司官网",
        "source_names": ["公司官网", "招聘页", "团队页", "博客", "技术白皮书"],
        "purpose": "产品、团队、技术方向",
        "talent_signals": ["产品路线", "技术栈", "团队负责人", "招聘方向", "客户案例"],
        "suggested_queries": [
            "site:company.com robotics embodied AI",
            "site:company.com careers robot learning",
            "site:company.com world model robotics",
        ],
        "access_pattern": "公开网页抓取前遵守 robots.txt；优先 RSS、站内搜索、公开新闻稿和招聘页。",
        "risk_level": "medium",
        "freshness": "weekly",
    },
    "github": {
        "name_zh": "GitHub",
        "source_names": ["GitHub"],
        "purpose": "工程能力、开源贡献",
        "talent_signals": ["代码质量", "开源贡献", "提交活跃度", "项目影响力", "机器人相关仓库"],
        "suggested_queries": [
            "diffusion policy robotics language:Python",
            "VLA robot policy",
            "MPC WBC locomotion",
        ],
        "access_pattern": "使用 GitHub API 或公开搜索；需要 token 时使用环境变量，不硬编码密钥。",
        "risk_level": "low",
        "freshness": "daily",
    },
    "model_hubs": {
        "name_zh": "Hugging Face / ModelScope",
        "source_names": ["Hugging Face", "ModelScope"],
        "purpose": "模型、数据集、Demo、Space 和开源影响力",
        "talent_signals": ["模型发布", "数据集贡献", "Space Demo", "下载量", "社区讨论"],
        "suggested_queries": [
            "robotics VLA dataset Hugging Face",
            "embodied AI policy ModelScope",
            "robot manipulation demo space",
        ],
        "access_pattern": "使用官方 API、公开项目页或人工整理；记录模型/数据集 license 和发布日期。",
        "risk_level": "low",
        "freshness": "daily",
    },
    "scholar_arxiv": {
        "name_zh": "Google Scholar / arXiv",
        "source_names": ["Google Scholar", "arXiv"],
        "purpose": "学术能力、论文方向",
        "talent_signals": ["论文主题", "作者", "引用", "机构", "研究方向演进"],
        "suggested_queries": [
            "embodied AI world model robotics",
            "vision language action robot manipulation",
            "model predictive control humanoid robot",
        ],
        "access_pattern": "arXiv 使用公开 API；Google Scholar 优先人工检索或合规第三方服务，不做高频抓取。",
        "risk_level": "medium",
        "freshness": "weekly",
    },
    "patent_databases": {
        "name_zh": "专利数据库",
        "source_names": ["Google Patents", "国家知识产权局", "Lens", "智慧芽"],
        "purpose": "技术发明人和公司技术布局",
        "talent_signals": ["发明人", "申请人", "技术方向", "专利族", "公司布局"],
        "suggested_queries": [
            "humanoid robot dexterous hand actuator",
            "robot world model motion planning",
            "机器人 灵巧手 触觉 发明人",
        ],
        "access_pattern": "优先公开检索、授权数据库 API 或人工导出；保留来源和公开状态。",
        "risk_level": "medium",
        "freshness": "monthly",
    },
    "business_databases_cn": {
        "name_zh": "企查查 / 天眼查",
        "source_names": ["企查查", "天眼查"],
        "purpose": "公司工商、融资、股权",
        "talent_signals": ["工商主体", "融资轮次", "股东", "高管", "关联公司"],
        "suggested_queries": [
            "具身智能 机器人 融资",
            "人形机器人 公司 股权",
            "机器人 创业公司 工商",
        ],
        "access_pattern": "使用官方商业接口或人工授权导出；不绕过付费墙或访问控制。",
        "risk_level": "high",
        "freshness": "weekly",
    },
    "news_media": {
        "name_zh": "新闻媒体",
        "source_names": ["36氪", "晚点", "机器之心", "量子位", "TechCrunch", "The Robot Report"],
        "purpose": "融资、产品发布、团队动态",
        "talent_signals": ["融资新闻", "产品发布", "核心成员", "客户合作", "战略变化"],
        "suggested_queries": [
            "具身智能 融资 团队",
            "humanoid robot funding team",
            "world model robotics product launch",
        ],
        "access_pattern": "使用公开 RSS、新闻搜索 API、站内搜索或授权媒体数据库；记录发布时间。",
        "risk_level": "low",
        "freshness": "daily",
    },
    "ai_communities": {
        "name_zh": "AI 社区 / 论坛",
        "source_names": ["AI 论坛", "Discord", "微信群", "知乎", "即刻", "Reddit"],
        "purpose": "年轻高潜人才、技术讨论、项目传播和社区影响力",
        "talent_signals": ["技术讨论", "项目分享", "社区声量", "同行推荐", "问题解法"],
        "suggested_queries": [
            "Reddit embodied AI robot learning",
            "知乎 具身智能 VLA 项目",
            "Discord robotics diffusion policy",
        ],
        "access_pattern": "优先使用公开页面、官方 API、授权社群整理或人工记录；不采集私域敏感信息。",
        "risk_level": "high",
        "freshness": "daily",
    },
    "ai_events": {
        "name_zh": "AI 活动 / 会议",
        "source_names": ["Hackathon", "Meetup", "会议", "直播", "Workshop"],
        "purpose": "活动参与者、演讲嘉宾、获奖项目和新兴团队线索",
        "talent_signals": ["参赛项目", "获奖名单", "演讲主题", "组织者", "Demo 展示"],
        "suggested_queries": [
            "robotics hackathon embodied AI winner",
            "具身智能 Meetup 机器人 Demo",
            "VLA Workshop speaker robotics",
        ],
        "access_pattern": "使用活动官网、公开议程、公开直播页或主办方授权名单；记录活动日期和来源。",
        "risk_level": "medium",
        "freshness": "per_event",
    },
    "video_platforms": {
        "name_zh": "视频平台 / 字幕",
        "source_names": ["B站", "YouTube", "技术演讲", "Demo 视频", "字幕"],
        "purpose": "Demo 真实性、技术讲解、公开演讲和项目影响力",
        "talent_signals": ["Demo 质量", "演讲内容", "字幕关键词", "项目作者", "互动反馈"],
        "suggested_queries": [
            "B站 具身智能 机器人 Demo",
            "YouTube robot manipulation VLA demo",
            "机器人 技术演讲 字幕 世界模型",
        ],
        "access_pattern": "优先使用官方 API、公开字幕、公开视频元数据或人工标注；保留 URL、发布时间和转写来源。",
        "risk_level": "medium",
        "freshness": "weekly",
    },
    "filings_annual_reports": {
        "name_zh": "招股书 / 年报",
        "source_names": ["招股书", "年报", "SEC", "港交所披露易", "巨潮资讯"],
        "purpose": "上市公司业务和人员情况",
        "talent_signals": ["业务收入", "研发投入", "员工结构", "核心技术", "风险因素"],
        "suggested_queries": [
            "机器人 年报 研发人员",
            "robotics annual report R&D headcount",
            "招股书 具身智能 机器人",
        ],
        "access_pattern": "使用交易所/监管机构公开披露文件，保留文件版本、日期和页码。",
        "risk_level": "low",
        "freshness": "quarterly",
    },
    "university_labs": {
        "name_zh": "学校实验室官网",
        "source_names": ["高校实验室官网", "导师主页", "课题组新闻"],
        "purpose": "高校人才来源",
        "talent_signals": ["学生去向", "研究项目", "导师方向", "论文与代码", "毕业生"],
        "suggested_queries": [
            "site:edu robotics manipulation lab students",
            "具身智能 实验室 学生 去向",
            "robot learning lab alumni",
        ],
        "access_pattern": "使用公开网页、RSS 或人工整理；尊重个人信息边界，只采集公开职业线索。",
        "risk_level": "medium",
        "freshness": "monthly",
    },
    "conference_paper_lists": {
        "name_zh": "会议论文名单",
        "source_names": ["ICRA", "IROS", "CoRL", "RSS", "CVPR", "NeurIPS"],
        "purpose": "ICRA、IROS、CoRL、RSS、CVPR、NeurIPS 等人才线索",
        "talent_signals": ["论文作者", "机构", "方向", "共同作者网络", "代码链接"],
        "suggested_queries": [
            "CoRL VLA robot manipulation authors",
            "RSS world model robot learning",
            "ICRA humanoid whole body control",
        ],
        "access_pattern": "使用会议开放论文列表、OpenReview、Semantic Scholar、DBLP 或官方 proceedings。",
        "risk_level": "low",
        "freshness": "per_conference",
    },
}
